### PR TITLE
Fix server crash on missing user

### LINKED ISSUE #54: The app is down because of internal bug
There is just loader spinnig when I try to access reportbot with this info in logs:

```
2020-08-11T07:57:03.073428+00:00 heroku[router]: at=info method=GET path="/api/tags" host=report.vacuumlabs.com request_id=049f4790-9bfa-4e57-96d9-7e032b7bd7bc fwd="217.73.18.218" dyno=web.1 connect=0ms service=427ms status=304 bytes=152 protocol=https
2020-08-11T07:57:08.813693+00:00 app[web.1]: (node:44) UnhandledPromiseRejectionWarning: Error: An API error occurred: user_not_found
2020-08-11T07:57:08.813704+00:00 app[web.1]:     at Object.platformErrorFromResult (/app/server/node_modules/@slack/web-api/dist/errors.js:50:33)
2020-08-11T07:57:08.813704+00:00 app[web.1]:     at WebClient.apiCall (/app/server/node_modules/@slack/web-api/dist/WebClient.js:486:28)
2020-08-11T07:57:08.813705+00:00 app[web.1]:     at runMicrotasks (<anonymous>)
2020-08-11T07:57:08.813705+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-11T07:57:08.813706+00:00 app[web.1]:     at async Object.load (/app/server/dist/index.js:40:13)
2020-08-11T07:57:08.813706+00:00 app[web.1]:     at async Object.get (/app/server/dist/cache.js:26:43)
2020-08-11T07:57:08.813706+00:00 app[web.1]:     at async Promise.all (index 150)
2020-08-11T07:57:08.813707+00:00 app[web.1]:     at async loadProfiles (/app/server/dist/index.js:86:20)
2020-08-11T07:57:08.813707+00:00 app[web.1]:     at async loadReportData (/app/server/dist/index.js:122:12)
2020-08-11T07:57:08.813766+00:00 app[web.1]: (node:44) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020-08-11T07:57:08.813818+00:00 app[web.1]: (node:44) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-08-11T07:57:13.827675+00:00 app[web.1]: (node:44) UnhandledPromiseRejectionWarning: Error: An API error occurred: user_not_found
2020-08-11T07:57:13.827685+00:00 app[web.1]:     at Object.platformErrorFromResult (/app/server/node_modules/@slack/web-api/dist/errors.js:50:33)
2020-08-11T07:57:13.827685+00:00 app[web.1]:     at WebClient.apiCall (/app/server/node_modules/@slack/web-api/dist/WebClient.js:486:28)
2020-08-11T07:57:13.827688+00:00 app[web.1]:     at runMicrotasks (<anonymous>)
2020-08-11T07:57:13.827689+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-11T07:57:13.827689+00:00 app[web.1]:     at async Object.load (/app/server/dist/index.js:40:13)
2020-08-11T07:57:13.827689+00:00 app[web.1]:     at async Object.get (/app/server/dist/cache.js:26:43)
2020-08-11T07:57:13.827690+00:00 app[web.1]:     at async Promise.all (index 150)
2020-08-11T07:57:13.827690+00:00 app[web.1]:     at async loadProfiles (/app/server/dist/index.js:86:20)
2020-08-11T07:57:13.827690+00:00 app[web.1]:     at async loadReportData (/app/server/dist/index.js:122:12)
2020-08-11T07:57:13.827691+00:00 app[web.1]:     at async /app/server/dist/index.js:129:12
2020-08-11T07:57:13.827708+00:00 app[web.1]: (node:44) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
2020-08-11T07:57:33.132530+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/api/reports" host=report.vacuumlabs.com request_id=4f2e235e-e945-4f3d-9611-f24c098e5ca4 fwd="217.73.18.218" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
```

### PR DESCRIPTION
**Pull request by leanil**
Fixes #54
Practice shows it's possible that a user mentioned in a message can't be queried by the bot through the API, causing the server to crash.
From the [docs](https://slack.com/intl/en-hu/help/articles/204475027-Deactivate-a-members-account) it seems like users can't be deleted entirely (just deactivated), so I guess the user (`U013G2ZH7EF`) is some special guest whom the bot hasn't right to access.

### CODE REVIEW

File: client/src/components/message/MessageContent.js [hunk 1]
```diff
@@ -40,7 +40,10 @@ class MessageContent extends Component {
       code: ({text}, k) => rich ? <code key={k}>{text}</code> : text,
       emoji: ({id}, k) => <Emoji name={id} customEmojis={customEmojis} key={k}/>,
       user: ({id}, k) => {
-        const name = `@${users[id].display_name}`
+        if (!users[id]) {
+          return `@${id}`
+        }
+        const name = `@${users[id].display_name || users[id].real_name}`
```
Comment (leanil) [inline client/src/components/message/MessageContent.js:46]: This is not related to the crash, but some users have `display_name === ""`, so only an `@` appeared.

Comment (paldys) [reply client/src/components/message/MessageContent.js:46]: Is it okay to do this?

Comment (leanil) [reply client/src/components/message/MessageContent.js:46]: To fix something not related to the issue being solved?
Or to display one's real name if they haven't set a display name?

Comment (paldys) [reply client/src/components/message/MessageContent.js:46]: :laughing: 

> To fix something not related to the issue being solved?

I mean, I would prefer if you mention it in the commit message, but okay. :smile: 

> Or to display one's real name if they haven't set a display name?

I was interested in this one.

Comment (paldys) [reply client/src/components/message/MessageContent.js:46]: Probably, this should work without a problem.

**Comment by paldys** [comment]
What about 
```
function MessageItem({message, customEmojis, users, channels}) {
  const author = users[message.user]
```
Can there be a problem when `author` is `null`? Can it be null?

File: client/src/components/message/MessageContent.js (hunk 1 above)
Comment (leanil) [reply client/src/components/message/MessageContent.js:46]: You can check anyone's real name on slack, so I don't see any problem with displaying it in the reports.

**Comment by leanil** [comment]
> Can there be a problem when `author` is `null`?

Definitely. Also if `firstReplyAuthor` is `null`.

> Can it be null?

I have no idea. As I wrote in the PR description, users shouldn't go missing in general, and I couldn't figure out what's special in the one causing the current crash.

I'm fine both with handling any possible missing data now, and with implementing a more specific solution later when we know what actually causes problem. Which one would you prefer?
In the first case, do you have any design preferences? (dummy profile pic vs none, dummy name vs none)

**Comment by paldys** [comment]
If I understand correctly, this bug causes the whole app to be unusable. If you are confident this will fix that and you can do a follow-up afterward, I am okay to approve it.

**Review by paldys — APPROVED** [review]

**Comment by leanil** [comment]
> If I understand correctly, this bug causes the whole app to be unusable. If you are confident this will fix that and you can do a follow-up afterward, I am okay to approve it.

Alright. So if the author user of some report would ever be missing, it would cause the client to crash on that specific project. In such case I'll dedicate time to
1. find out who's the person missing and why is he/she not accessible through the API
2. possibly upgrade the bot to the new permission system
